FROM openproject/community:13

# Clonar el plugin directamente en la carpeta de plugins de OpenProject
RUN git clone https://github.com/btey/openproject-gitlab-integration.git /opt/openproject/plugins/openproject-gitlab-integration
